version: '3.8'
include: 
  - 'docker-compose.dev.yml'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
